<?php

return [
    'profile' => [
        'model' => 'Profile',
        'table' => 'profiles',
        'fields' => [
            'slug' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255', 'regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/'], 'unique' => true],
            'name' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'headline' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'introduction' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
            'biography' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'location' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'public_email' => ['type' => 'email', 'required' => false, 'rules' => ['nullable', 'string', 'max:255', 'email'], 'unique' => false],
            'phone' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:50'], 'unique' => false],
            'availability' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'logo_media_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:media,id'], 'unique' => false, 'reference' => 'media'],
            'avatar_media_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:media,id'], 'unique' => false, 'reference' => 'media'],
            'focus' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'learning' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'philosophy' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
        ],
        'relations' => ['avatar', 'logo'],
    ],
    'social-links' => [
        'model' => 'SocialLink',
        'table' => 'social_links',
        'fields' => [
            'platform' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:80'], 'unique' => false],
            'label' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'url' => ['type' => 'url', 'required' => true, 'rules' => ['required', 'string', 'max:10000', 'url:http,https'], 'unique' => false],
            'sort_order' => ['type' => 'number', 'required' => false, 'rules' => ['sometimes', 'integer', 'min:0', 'max:2147483647'], 'unique' => false, 'default' => 0],
            'is_visible' => ['type' => 'checkbox', 'required' => false, 'rules' => ['sometimes', 'boolean'], 'unique' => false, 'default' => false],
        ],
        'relations' => [],
    ],
    'resumes' => [
        'model' => 'Resume',
        'table' => 'resumes',
        'fields' => [
            'title' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'media_id' => ['type' => 'reference', 'required' => true, 'rules' => ['required', 'integer', 'exists:media,id'], 'unique' => false, 'reference' => 'media'],
            'locale' => ['type' => 'text', 'required' => false, 'rules' => ['sometimes', 'string', 'max:20'], 'unique' => false, 'default' => 'en'],
            'is_visible' => ['type' => 'checkbox', 'required' => false, 'rules' => ['sometimes', 'boolean'], 'unique' => false, 'default' => true],
        ],
        'relations' => ['media'],
    ],
    'site-settings' => [
        'model' => 'SiteSetting',
        'table' => 'site_settings',
        'fields' => [
            'key' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => true],
            'value' => ['type' => 'json', 'required' => false, 'rules' => ['nullable', 'array'], 'unique' => false],
            'is_public' => ['type' => 'checkbox', 'required' => false, 'rules' => ['sometimes', 'boolean'], 'unique' => false, 'default' => false],
        ],
        'relations' => [],
    ],
    'skill-categories' => [
        'model' => 'SkillCategory',
        'table' => 'skill_categories',
        'fields' => [
            'name' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'slug' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255', 'regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/'], 'unique' => true],
            'description' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
            'sort_order' => ['type' => 'number', 'required' => false, 'rules' => ['sometimes', 'integer', 'min:0', 'max:2147483647'], 'unique' => false, 'default' => 0],
        ],
        'relations' => [],
    ],
    'skills' => [
        'model' => 'Skill',
        'table' => 'skills',
        'fields' => [
            'skill_category_id' => ['type' => 'reference', 'required' => true, 'rules' => ['required', 'integer', 'exists:skill_categories,id'], 'unique' => false, 'reference' => 'skill_categories'],
            'name' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'slug' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255', 'regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/'], 'unique' => true],
            'description' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
            'sort_order' => ['type' => 'number', 'required' => false, 'rules' => ['sometimes', 'integer', 'min:0', 'max:2147483647'], 'unique' => false, 'default' => 0],
            'is_visible' => ['type' => 'checkbox', 'required' => false, 'rules' => ['sometimes', 'boolean'], 'unique' => false, 'default' => false],
            'icon' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'proficiency' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:80'], 'unique' => false],
        ],
        'relations' => ['category'],
    ],
    'project-categories' => [
        'model' => 'ProjectCategory',
        'table' => 'project_categories',
        'fields' => [
            'name' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'slug' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255', 'regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/'], 'unique' => true],
            'description' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
            'sort_order' => ['type' => 'number', 'required' => false, 'rules' => ['sometimes', 'integer', 'min:0', 'max:2147483647'], 'unique' => false, 'default' => 0],
        ],
        'relations' => [],
    ],
    'technologies' => [
        'model' => 'Technology',
        'table' => 'technologies',
        'fields' => [
            'name' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'slug' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255', 'regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/'], 'unique' => true],
            'website_url' => ['type' => 'url', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000', 'url:http,https'], 'unique' => false],
        ],
        'relations' => [],
    ],
    'projects' => [
        'model' => 'Project',
        'table' => 'projects',
        'fields' => [
            'project_category_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:project_categories,id'], 'unique' => false, 'reference' => 'project_categories'],
            'cover_media_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:media,id'], 'unique' => false, 'reference' => 'media'],
            'title' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'slug' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255', 'regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/'], 'unique' => true],
            'summary' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
            'description' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'problem' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'solution' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'architecture' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'challenges' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'outcomes' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'role' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'status' => ['type' => 'select', 'required' => false, 'rules' => ['nullable', 'string', 'in:planned,in_progress,completed,maintained,archived,prototype,research'], 'unique' => false, 'options' => ['planned', 'in_progress', 'completed', 'maintained', 'archived', 'prototype', 'research']],
            'repository_url' => ['type' => 'url', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000', 'url:http,https'], 'unique' => false],
            'demo_url' => ['type' => 'url', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000', 'url:http,https'], 'unique' => false],
            'started_on' => ['type' => 'date', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'ended_on' => ['type' => 'date', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'is_featured' => ['type' => 'checkbox', 'required' => false, 'rules' => ['sometimes', 'boolean'], 'unique' => false, 'default' => false],
            'sort_order' => ['type' => 'number', 'required' => false, 'rules' => ['sometimes', 'integer', 'min:0', 'max:2147483647'], 'unique' => false, 'default' => 0],
            'published_at' => ['type' => 'datetime-local', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'target_users' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'key_features' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'database_design' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'api_architecture' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'lessons_learned' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'future_improvements' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'architecture_media_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:media,id'], 'unique' => false, 'reference' => 'media'],
            'database_media_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:media,id'], 'unique' => false, 'reference' => 'media'],
            'technology_ids' => ['type' => 'multi-reference', 'required' => false, 'rules' => ['sometimes', 'array', 'max:100'], 'reference' => 'technologies', 'relation' => 'technologies'],
            'media_ids' => ['type' => 'multi-reference', 'required' => false, 'rules' => ['sometimes', 'array', 'max:100'], 'reference' => 'media', 'relation' => 'gallery'],
        ],
        'relations' => ['category', 'cover', 'architectureImage', 'databaseImage', 'technologies', 'gallery'],
    ],
    'experience' => [
        'model' => 'Experience',
        'table' => 'experiences',
        'fields' => [
            'organization' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'role' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'employment_type' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:80'], 'unique' => false],
            'location' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'organization_url' => ['type' => 'url', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000', 'url:http,https'], 'unique' => false],
            'started_on' => ['type' => 'date', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'ended_on' => ['type' => 'date', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'is_current' => ['type' => 'checkbox', 'required' => false, 'rules' => ['sometimes', 'boolean'], 'unique' => false, 'default' => false],
            'description' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'sort_order' => ['type' => 'number', 'required' => false, 'rules' => ['sometimes', 'integer', 'min:0', 'max:2147483647'], 'unique' => false, 'default' => 0],
            'published_at' => ['type' => 'datetime-local', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'responsibilities' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'logo_media_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:media,id'], 'unique' => false, 'reference' => 'media'],
            'technology_ids' => ['type' => 'multi-reference', 'required' => false, 'rules' => ['sometimes', 'array', 'max:100'], 'reference' => 'technologies', 'relation' => 'technologies'],
        ],
        'relations' => ['logo', 'technologies'],
    ],
    'education' => [
        'model' => 'Education',
        'table' => 'educations',
        'fields' => [
            'institution' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'qualification' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'field_of_study' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'location' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'started_on' => ['type' => 'date', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'ended_on' => ['type' => 'date', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'is_current' => ['type' => 'checkbox', 'required' => false, 'rules' => ['sometimes', 'boolean'], 'unique' => false, 'default' => false],
            'description' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'sort_order' => ['type' => 'number', 'required' => false, 'rules' => ['sometimes', 'integer', 'min:0', 'max:2147483647'], 'unique' => false, 'default' => 0],
            'published_at' => ['type' => 'datetime-local', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'coursework' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
        ],
        'relations' => [],
    ],
    'certifications' => [
        'model' => 'Certification',
        'table' => 'certifications',
        'fields' => [
            'name' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'issuer' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'credential_id' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'credential_url' => ['type' => 'url', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000', 'url:http,https'], 'unique' => false],
            'issued_on' => ['type' => 'date', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'expires_on' => ['type' => 'date', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'description' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
            'media_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:media,id'], 'unique' => false, 'reference' => 'media'],
            'sort_order' => ['type' => 'number', 'required' => false, 'rules' => ['sometimes', 'integer', 'min:0', 'max:2147483647'], 'unique' => false, 'default' => 0],
            'published_at' => ['type' => 'datetime-local', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'pdf_media_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:media,id'], 'unique' => false, 'reference' => 'media'],
        ],
        'relations' => ['media', 'pdf'],
    ],
    'blog-categories' => [
        'model' => 'ArticleCategory',
        'table' => 'article_categories',
        'fields' => [
            'name' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'slug' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255', 'regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/'], 'unique' => true],
            'description' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
        ],
        'relations' => [],
    ],
    'blog-tags' => [
        'model' => 'Tag',
        'table' => 'tags',
        'fields' => [
            'name' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'slug' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255', 'regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/'], 'unique' => true],
        ],
        'relations' => [],
    ],
    'blog' => [
        'model' => 'Article',
        'table' => 'articles',
        'fields' => [
            'article_category_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:article_categories,id'], 'unique' => false, 'reference' => 'article_categories'],
            'cover_media_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:media,id'], 'unique' => false, 'reference' => 'media'],
            'title' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'slug' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255', 'regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/'], 'unique' => true],
            'excerpt' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
            'body' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'meta_title' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'meta_description' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
            'is_featured' => ['type' => 'checkbox', 'required' => false, 'rules' => ['sometimes', 'boolean'], 'unique' => false, 'default' => false],
            'published_at' => ['type' => 'datetime-local', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'project_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:projects,id'], 'unique' => false, 'reference' => 'projects'],
            'repository_url' => ['type' => 'url', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000', 'url:http,https'], 'unique' => false],
            'technology_ids' => ['type' => 'multi-reference', 'required' => false, 'rules' => ['sometimes', 'array', 'max:100'], 'reference' => 'technologies', 'relation' => 'technologies'],
            'tag_ids' => ['type' => 'multi-reference', 'required' => false, 'rules' => ['sometimes', 'array', 'max:100'], 'reference' => 'tags', 'relation' => 'tags'],
            'media_ids' => ['type' => 'multi-reference', 'required' => false, 'rules' => ['sometimes', 'array', 'max:100'], 'reference' => 'media', 'relation' => 'gallery'],
        ],
        'relations' => ['category', 'cover', 'project', 'tags', 'technologies', 'gallery'],
        'type' => 'blog',
    ],
    'contact-messages' => [
        'model' => 'ContactMessage',
        'table' => 'contact_messages',
        'fields' => [
            'name' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'email' => ['type' => 'email', 'required' => true, 'rules' => ['required', 'string', 'max:255', 'email'], 'unique' => false],
            'subject' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'message' => ['type' => 'textarea', 'required' => true, 'rules' => ['required', 'string', 'max:10000'], 'unique' => false],
            'status' => ['type' => 'select', 'required' => false, 'rules' => ['sometimes', 'string', 'in:unread,read,replied,archived,spam'], 'unique' => false, 'options' => ['unread', 'read', 'replied', 'archived', 'spam'], 'default' => 'unread'],
            'admin_notes' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
            'read_at' => ['type' => 'datetime-local', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'replied_at' => ['type' => 'datetime-local', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
        ],
        'relations' => [],
    ],
    'engineering' => [
        'model' => 'Article',
        'table' => 'articles',
        'fields' => [
            'article_category_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:article_categories,id'], 'unique' => false, 'reference' => 'article_categories'],
            'cover_media_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:media,id'], 'unique' => false, 'reference' => 'media'],
            'title' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255'], 'unique' => false],
            'slug' => ['type' => 'text', 'required' => true, 'rules' => ['required', 'string', 'max:255', 'regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/'], 'unique' => true],
            'excerpt' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
            'body' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:100000'], 'unique' => false],
            'meta_title' => ['type' => 'text', 'required' => false, 'rules' => ['nullable', 'string', 'max:255'], 'unique' => false],
            'meta_description' => ['type' => 'textarea', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000'], 'unique' => false],
            'is_featured' => ['type' => 'checkbox', 'required' => false, 'rules' => ['sometimes', 'boolean'], 'unique' => false, 'default' => false],
            'published_at' => ['type' => 'datetime-local', 'required' => false, 'rules' => ['nullable', 'date'], 'unique' => false],
            'project_id' => ['type' => 'reference', 'required' => false, 'rules' => ['nullable', 'integer', 'exists:projects,id'], 'unique' => false, 'reference' => 'projects'],
            'repository_url' => ['type' => 'url', 'required' => false, 'rules' => ['nullable', 'string', 'max:10000', 'url:http,https'], 'unique' => false],
            'technology_ids' => ['type' => 'multi-reference', 'required' => false, 'rules' => ['sometimes', 'array', 'max:100'], 'reference' => 'technologies', 'relation' => 'technologies'],
            'tag_ids' => ['type' => 'multi-reference', 'required' => false, 'rules' => ['sometimes', 'array', 'max:100'], 'reference' => 'tags', 'relation' => 'tags'],
            'media_ids' => ['type' => 'multi-reference', 'required' => false, 'rules' => ['sometimes', 'array', 'max:100'], 'reference' => 'media', 'relation' => 'gallery'],
        ],
        'relations' => ['category', 'cover', 'project', 'tags', 'technologies', 'gallery'],
        'type' => 'engineering',
    ],
];
